WebApplication1/Models/Сотрудники.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Сотрудники
    {
        [Key]
        public int ID_Сотрудника { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Отчество { get; set; }
        public Nullable<int> Телефон { get; set; }
        public string Должность { get; set; }
        public string Общий_стаж { get; set; }
        public Nullable<decimal> Зарплата { get; set; }
        public Nullable<int> ID_Спорт_клуба { get; set; }
    
        public virtual Спортивный_клуб Спортивный_клуб { get; set; }
        //public virtual Тренер Тренер { get; set; }
    }
}

WebApplication1/Controllers/СотрудникиController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class СотрудникиController : Controller
    {
        private DBConnection db = new DBConnection();

   
        public ActionResult Index(string filter)
        {
            if (!String.IsNullOrWhiteSpace(filter))
            {
                var temp = db.Сотрудники.AsEnumerable();

                temp = temp.Where(x => x.Фамилия == filter);
                return View(temp.ToList());

            }

            var сотрудники = db.Сотрудники.Include(с => с.Спортивный_клуб);
            return View(сотрудники.ToList());

        }


        // GET: Сотрудники
        //public ActionResult Index()
        //{
        //    var сотрудники = db.Сотрудники.Include(с => с.Спортивный_клуб);
        //    return View(сотрудники.ToList());
        //}

        // GET: Сотрудники/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Сотрудники сотрудники = db.Сотрудники.Find(id);
            if (сотрудники == null)
            {
                return HttpNotFound();
            }
            return View(сотрудники);
        }

        // GET: Сотрудники/Create
        public ActionResult Create()
        {
            ViewBag.ID_Спорт_клуба = new SelectList(db.Спортивный_клуб, "ID_Спорт_клуба", "Название");
            return View();
        }

        // POST: Сотрудники/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Сотрудника,Имя,Фамилия,Отчество,Телефон,Должность,Общий_стаж,Зарплата,ID_Спорт_клуба")] Сотрудники сотрудники)
        {
            if (ModelState.IsValid)
            {
                db.Сотрудники.Add(сотрудники);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_Спорт_клуба = new SelectList(db.Спортивный_клуб, "ID_Спорт_клуба", "Название", сотрудники.ID_Спорт_клуба);
            return View(сотрудники);
        }

        // GET: Сотрудники/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Сотрудники сотрудники = db.Сотрудники.Find(id);
            if (сотрудники == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_Спорт_клуба = new SelectList(db.Спортивный_клуб, "ID_Спорт_клуба", "Название", сотрудники.ID_Спорт_клуба);
            return View(сотрудники);
        }

        // POST: Сотрудники/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Сотрудника,Имя,Фамилия,Отчество,Телефон,Должность,Общий_стаж,Зарплата,ID_Спорт_клуба")] Сотрудники сотрудники)
        {
            if (ModelState.IsValid)
            {
                db.Entry(сотрудники).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_Спорт_клуба = new SelectList(db.Спортивный_клуб, "ID_Спорт_клуба", "Название", сотрудники.ID_Спорт_клуба);
            return View(сотрудники);
        }

        // GET: Сотрудники/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Сотрудники сотрудники = db.Сотрудники.Find(id);
            if (сотрудники == null)
            {
                return HttpNotFound();
            }
            return View(сотрудники);
        }

        // POST: Сотрудники/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Сотрудники сотрудники = db.Сотрудники.Find(id);
            db.Сотрудники.Remove(сотрудники);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Сотрудники/Create.cshtml
@model WebApplication1.Models.Сотрудники

@{
    ViewBag.Title = "Create";
}

<h2>Создание</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Сотрудники</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Имя, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Имя, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Имя, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Фамилия, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Фамилия, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Фамилия, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Отчество, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Отчество, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Отчество, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Телефон, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Телефон, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Телефон, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Должность, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Должность, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Должность, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Общий_стаж, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Общий_стаж, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Общий_стаж, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Зарплата, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Зарплата, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Зарплата, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Спорт_клуба, "ID_Спорт_клуба", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Спорт_клуба", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Спорт_клуба, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к таблице", "Index")
</div>

WebApplication1/Views/Сотрудники/Delete.cshtml
@model WebApplication1.Models.Сотрудники

@{
    ViewBag.Title = "Delete";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить?</h3>
<div>
    <h4>Сотрудники</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Спортивный_клуб.Название)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Спортивный_клуб.Название)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Имя)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Имя)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Фамилия)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Фамилия)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Отчество)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Отчество)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Телефон)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Телефон)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Должность)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Должность)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Общий_стаж)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Общий_стаж)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Зарплата)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Зарплата)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к таблице", "Index")
        </div>
    }
</div>

WebApplication1/Views/Сотрудники/Details.cshtml
@model WebApplication1.Models.Сотрудники

@{
    ViewBag.Title = "Details";
}

<h2>Подробно</h2>

<div>
    <h4>Сотрудники</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Спортивный_клуб.Название)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Спортивный_клуб.Название)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Имя)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Имя)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Фамилия)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Фамилия)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Отчество)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Отчество)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Телефон)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Телефон)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Должность)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Должность)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Общий_стаж)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Общий_стаж)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Зарплата)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Зарплата)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.ID_Сотрудника }) |
    @Html.ActionLink("Вернуться к таблице", "Index")
</p>

WebApplication1/Views/Сотрудники/Edit.cshtml
@model WebApplication1.Models.Сотрудники

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Сотрудники</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Сотрудника)

        <div class="form-group">
            @Html.LabelFor(model => model.Имя, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Имя, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Имя, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Фамилия, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Фамилия, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Фамилия, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Отчество, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Отчество, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Отчество, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Телефон, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Телефон, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Телефон, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Должность, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Должность, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Должность, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Общий_стаж, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Общий_стаж, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Общий_стаж, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Зарплата, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Зарплата, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Зарплата, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_Спорт_клуба, "ID_Спорт_клуба", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_Спорт_клуба", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_Спорт_клуба, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к таблице", "Index")
</div>

WebApplication1/Views/Сотрудники/Index.cshtml
@model IEnumerable<WebApplication1.Models.Сотрудники>

@{
    ViewBag.Title = "Index";
}

<h2>Сотрудники</h2>

<p>
    @Html.ActionLink("Создать", "Create")

    @using (@Html.BeginForm("Index", "Сотрудники"))
    {
        @Html.TextBox("filter", "", new { style = "width:100%" })
        <br />
        <input type="submit" class="btn btn-primary" value="Отфильтровать по фамилии" />
    }
</p>

<table class="table">
    <tr>
        <th>
            @*@Html.DisplayNameFor(model => model.Спортивный_клуб.Название)*@
            Название Спортивного_клуба
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Имя)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Фамилия)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Отчество)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Телефон)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Должность)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Общий_стаж)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Зарплата)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Спортивный_клуб.Название)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Имя)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Фамилия)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Отчество)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Телефон)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Должность)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Общий_стаж)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Зарплата)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id=item.ID_Сотрудника }) |
            @Html.ActionLink("Подробнее", "Details", new { id=item.ID_Сотрудника }) |
            @Html.ActionLink("Удалить", "Delete", new { id=item.ID_Сотрудника })
        </td>
    </tr>
}

</table>