WebApplication1/Models/Спортивный_клуб.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Спортивный_клуб
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Спортивный_клуб()
        {
            //this.Подготовка_к_соревнованиям = new HashSet<Подготовка_к_соревнованиям>();
            this.Сотрудники = new HashSet<Сотрудники>();
        }
        [Key, ForeignKey("Сотрудники")]
        public int ID_Спорт_клуба { get; set; }
        public string Название { get; set; }
        public string Адрес { get; set; }
        public Nullable<int> Телефон { get; set; }
        public Nullable<bool> Сауна { get; set; }
        public Nullable<bool> Тренажерный_зал { get; set; }
        public Nullable<bool> Бассейн { get; set; }
        public Nullable<bool> Бар { get; set; }
        public Nullable<bool> Массажный_кабинет { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<DateTime> Дата_основания { get; set; }
    
       // public virtual Владелец Владелец { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        //public virtual ICollection<Подготовка_к_соревнованиям> Подготовка_к_соревнованиям { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудники> Сотрудники { get; set; }
        public virtual ICollection<Спортсмен> Спортсменs { get; set; }
    }
}

WebApplication1/Controllers/Спортивный_клубController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class Спортивный_клубController : Controller
    {
        private DBConnection db = new DBConnection();

        public interface IExceptionFilter
        {
            void OnException(ExceptionContext filterContext);
        }

        // GET: Спортивный_клуб
        public ActionResult Index(string search)
        {
            return View(db.Спортивный_клуб.Where(x => x.Название.Contains(search) || search == null).ToList());
            //return View(db.Спортивный_клуб.ToList());
        }

        // GET: Спортивный_клуб/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Спортивный_клуб спортивный_клуб = db.Спортивный_клуб.Find(id);
            if (спортивный_клуб == null)
            {
                return HttpNotFound();
            }
            return View(спортивный_клуб);
        }

        // GET: Спортивный_клуб/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Спортивный_клуб/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Спорт_клуба,Название,Адрес,Телефон,Сауна,Тренажерный_зал,Бассейн,Бар,Массажный_кабинет,Дата_основания")] Спортивный_клуб спортивный_клуб)
        {
            if (ModelState.IsValid)
            {
                db.Спортивный_клуб.Add(спортивный_клуб);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(спортивный_клуб);
        }

        // GET: Спортивный_клуб/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Спортивный_клуб спортивный_клуб = db.Спортивный_клуб.Find(id);
            if (спортивный_клуб == null)
            {
                return HttpNotFound();
            }
            return View(спортивный_клуб);
        }

        // POST: Спортивный_клуб/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Спорт_клуба,Название,Адрес,Телефон,Сауна,Тренажерный_зал,Бассейн,Бар,Массажный_кабинет,Дата_основания")] Спортивный_клуб спортивный_клуб)
        {
            if (ModelState.IsValid)
            {
                db.Entry(спортивный_клуб).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(спортивный_клуб);
        }

        // GET: Спортивный_клуб/Delete/5
        [HandleError(ExceptionType = typeof(DeletedRowInaccessibleException), View = "~/Error")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Спортивный_клуб спортивный_клуб = db.Спортивный_клуб.Find(id);
            if (спортивный_клуб == null)
            {
                return HttpNotFound();
            }
            return View(спортивный_клуб);
        }

        // POST: Спортивный_клуб/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [HandleError(ExceptionType = typeof(DeletedRowInaccessibleException), View = "~/Error")]
        public ActionResult DeleteConfirmed(int id)
        {
            try { 
            Спортивный_клуб спортивный_клуб = db.Спортивный_клуб.Find(id);
            db.Спортивный_клуб.Remove(спортивный_клуб);
            db.SaveChanges();
            return RedirectToAction("Index");
            } catch
            {
                return Redirect("~/Спортивный_клуб/Error/");                             
            }
        }

        public ActionResult Error()
        {
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Спортивный_клуб/Create.cshtml
@model WebApplication1.Models.Спортивный_клуб

@{
    ViewBag.Title = "Create";
}

<h2>Создание</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Спортивный_клуб</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Название, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Название, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Название, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Адрес, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Адрес, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Адрес, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Телефон, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Телефон, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Телефон, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Сауна, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Сауна)
                    @Html.ValidationMessageFor(model => model.Сауна, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Тренажерный_зал, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Тренажерный_зал)
                    @Html.ValidationMessageFor(model => model.Тренажерный_зал, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Бассейн, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Бассейн)
                    @Html.ValidationMessageFor(model => model.Бассейн, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Бар, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Бар)
                    @Html.ValidationMessageFor(model => model.Бар, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Массажный_кабинет, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Массажный_кабинет)
                    @Html.ValidationMessageFor(model => model.Массажный_кабинет, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Дата_основания, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Дата_основания, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Дата_основания, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к таблице", "Index")
</div>

WebApplication1/Views/Спортивный_клуб/Delete.cshtml
@model WebApplication1.Models.Спортивный_клуб

@{
    ViewBag.Title = "Delete";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить?</h3>
<div>
    <h4>Спортивный_клуб</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Название)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Название)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Адрес)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Адрес)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Телефон)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Телефон)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Сауна)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Сауна)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Тренажерный_зал)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Тренажерный_зал)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Бассейн)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Бассейн)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Бар)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Бар)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Массажный_кабинет)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Массажный_кабинет)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Дата_основания)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Дата_основания)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к таблице", "Index")
        </div>
    }
</div>

WebApplication1/Views/Спортивный_клуб/Details.cshtml
@model WebApplication1.Models.Спортивный_клуб

@{
    ViewBag.Title = "Details";
}

<h2>Подробно</h2>

<div>
    <h4>Спортивный_клуб</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Название)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Название)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Адрес)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Адрес)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Телефон)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Телефон)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Сауна)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Сауна)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Тренажерный_зал)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Тренажерный_зал)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Бассейн)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Бассейн)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Бар)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Бар)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Массажный_кабинет)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Массажный_кабинет)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Дата_основания)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Дата_основания)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.ID_Спорт_клуба }) |
    @Html.ActionLink("Вернуться к таблице", "Index")
</p>

WebApplication1/Views/Спортивный_клуб/Edit.cshtml
@model WebApplication1.Models.Спортивный_клуб

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Спортивный_клуб</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Спорт_клуба)

        <div class="form-group">
            @Html.LabelFor(model => model.Название, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Название, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Название, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Адрес, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Адрес, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Адрес, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Телефон, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Телефон, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Телефон, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Сауна, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Сауна)
                    @Html.ValidationMessageFor(model => model.Сауна, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Тренажерный_зал, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Тренажерный_зал)
                    @Html.ValidationMessageFor(model => model.Тренажерный_зал, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Бассейн, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Бассейн)
                    @Html.ValidationMessageFor(model => model.Бассейн, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Бар, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Бар)
                    @Html.ValidationMessageFor(model => model.Бар, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Массажный_кабинет, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Массажный_кабинет)
                    @Html.ValidationMessageFor(model => model.Массажный_кабинет, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Дата_основания, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Дата_основания, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Дата_основания, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к таблице", "Index")
</div>

WebApplication1/Views/Спортивный_клуб/Index.cshtml
@model IEnumerable<WebApplication1.Models.Спортивный_клуб>

@{
    ViewBag.Title = "Index";
}

<h2>Спортивный клуб</h2>

<p>
    @Html.ActionLink("Создать", "Create")

    @using (@Html.BeginForm("Index", "Спортивный_клуб"))
    {
        @Html.TextBox("search", "", new { style = "width:100%" })
        <br />
        <input type="submit" class="btn btn-primary" value="Найти по названию" />
    }

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Название)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Адрес)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Телефон)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Сауна)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Тренажерный_зал)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Бассейн)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Бар)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Массажный_кабинет)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Дата_основания)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Название)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Адрес)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Телефон)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Сауна)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Тренажерный_зал)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Бассейн)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Бар)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Массажный_кабинет)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Дата_основания)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id=item.ID_Спорт_клуба }) |
            @Html.ActionLink("Подробнее", "Details", new { id=item.ID_Спорт_клуба }) |
            @Html.ActionLink("Удалить", "Delete", new { id=item.ID_Спорт_клуба })
        </td>
    </tr>
}

</table>