WebApplication1/Models/Спортсмен.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Спортсмен
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ID_Спортсмена { get; set; }
  
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public Nullable<bool> Пол { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Группа { get; set; }
        public Nullable<int> Телефон { get; set; }
        public string Гражданство { get; set; }
        public ulong Серия_номер_паспорта { get; set; }
        public string Адрес_проживания { get; set; }
                     
        //public virtual Договор Договор { get; set; }


    }
}

WebApplication1/Controllers/СпортсменController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class СпортсменController : Controller
    {
        private DBConnection db = new DBConnection();

        // GET: Спортсмен
        public ActionResult Index(string search, string filter)
        {
            if (!String.IsNullOrWhiteSpace(filter))
            {
                var temp = db.Спортсмен.AsEnumerable();

                temp = temp.Where(x => x.Гражданство == filter);
                return View(temp.ToList());

            }
            return View(db.Спортсмен.Where(x => x.Фамилия.Contains(search) || search == null).ToList());
           // return View(db.Спортсмен.ToList());
        }
        

        // GET: Спортсмен/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Спортсмен спортсмен = db.Спортсмен.Find(id);
            if (спортсмен == null)
            {
                return HttpNotFound();
            }
            return View(спортсмен);
        }

        // GET: Спортсмен/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Спортсмен/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Спортсмена,Имя,Фамилия,Пол,Дата_рождения,Группа,Телефон,Гражданство,Адрес_проживания")] Спортсмен спортсмен)
        {
            if (ModelState.IsValid)
            {
                db.Спортсмен.Add(спортсмен);
                db.SaveChanges();

                db.Database.ExecuteSqlCommand("EXEC TestAge");

                return RedirectToAction("Index");
            }

            return View(спортсмен);
        }

        // GET: Спортсмен/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Спортсмен спортсмен = db.Спортсмен.Find(id);
            if (спортсмен == null)
            {
                return HttpNotFound();
            }
            return View(спортсмен);
        }

        // POST: Спортсмен/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Спортсмена,Имя,Фамилия,Пол,Дата_рождения,Группа,Телефон,Гражданство,Адрес_проживания")] Спортсмен спортсмен)
        {
            if (ModelState.IsValid)
            {
                db.Entry(спортсмен).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(спортсмен);
        }

        // GET: Спортсмен/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Спортсмен спортсмен = db.Спортсмен.Find(id);
            if (спортсмен == null)
            {
                return HttpNotFound();
            }
            return View(спортсмен);
        }

        // POST: Спортсмен/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Спортсмен спортсмен = db.Спортсмен.Find(id);
            db.Спортсмен.Remove(спортсмен);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Спортсмен/Create.cshtml
@model WebApplication1.Models.Спортсмен

@{
    ViewBag.Title = "Create";
}

<h2>Создание</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Спортсмен</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Имя, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Имя, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Имя, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Фамилия, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Фамилия, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Фамилия, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Пол, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Пол)
                @Html.ValidationMessageFor(model => model.Пол, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Дата_рождения, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Дата_рождения, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Дата_рождения, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.Группа, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Группа, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Группа, "", new { @class = "text-danger" })
        </div>
    </div>*@

    <div class="form-group">
        @Html.LabelFor(model => model.Телефон, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Телефон, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Телефон, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Гражданство, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Гражданство, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Гражданство, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Адрес_проживания, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Адрес_проживания, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Адрес_проживания, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Создать" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Вернуться к таблице", "Index")
</div>

WebApplication1/Views/Спортсмен/Delete.cshtml
@model WebApplication1.Models.Спортсмен

@{
    ViewBag.Title = "Delete";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить?</h3>
<div>
    <h4>Спортсмен</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Имя)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Имя)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Фамилия)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Фамилия)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Пол)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Пол)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Дата_рождения)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Дата_рождения)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Группа)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Группа)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Телефон)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Телефон)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Гражданство)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Гражданство)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Адрес_проживания)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Адрес_проживания)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к таблице", "Index")
        </div>
    }
</div>

WebApplication1/Views/Спортсмен/Details.cshtml
@model WebApplication1.Models.Спортсмен

@{
    ViewBag.Title = "Details";
}

<h2>Подробно</h2>

<div>
    <h4>Спортсмен</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Имя)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Имя)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Фамилия)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Фамилия)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Пол)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Пол)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Дата_рождения)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Дата_рождения)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Группа)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Группа)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Телефон)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Телефон)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Гражданство)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Гражданство)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Адрес_проживания)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Адрес_проживания)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.ID_Спортсмена }) |
    @Html.ActionLink("Вернуться к таблице", "Index")
</p>

WebApplication1/Views/Спортсмен/Edit.cshtml
@model WebApplication1.Models.Спортсмен

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Спортсмен</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ID_Спортсмена)

    <div class="form-group">
        @Html.LabelFor(model => model.Имя, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Имя, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Имя, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Фамилия, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Фамилия, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Фамилия, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Пол, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Пол)
                @Html.ValidationMessageFor(model => model.Пол, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Дата_рождения, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Дата_рождения, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Дата_рождения, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Группа, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Группа, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Группа, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Телефон, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Телефон, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Телефон, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Гражданство, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Гражданство, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Гражданство, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Адрес_проживания, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Адрес_проживания, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Адрес_проживания, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Вернуться к таблице", "Index")
</div>

WebApplication1/Views/Спортсмен/Index.cshtml
@model IEnumerable<WebApplication1.Models.Спортсмен>

@{
    ViewBag.Title = "Index";
}

<h2>Спортсмен</h2>

<p>
    @Html.ActionLink("Создать", "Create")
    @using (@Html.BeginForm("Index", "Спортсмен"))
    {
        @Html.TextBox("search", "", new { style = "width:100%" })
        <br />
        <input type="submit" class="btn btn-primary" value="Найти по фамилии" />
    }
    <br />
    @using (@Html.BeginForm("Index", "Спортсмен"))
    {
        @Html.TextBox("filter", "", new { style = "width:100%" })
        <br />
        <input type="submit" class="btn btn-primary" value="Отфильтровать по гражданству" />
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Имя)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Фамилия)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Пол)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Дата_рождения)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Группа)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Телефон)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Гражданство)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Адрес_проживания)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Имя)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Фамилия)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Пол)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Дата_рождения)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Группа)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Телефон)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Гражданство)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Адрес_проживания)
    </td>
    <td>
        @Html.ActionLink("Редактировать", "Edit", new { id = item.ID_Спортсмена }) |
        @Html.ActionLink("Подробнее", "Details", new { id = item.ID_Спортсмена }) |
        @Html.ActionLink("Удалить", "Delete", new { id = item.ID_Спортсмена })
    </td>
</tr>
}

</table>