WebApplication1/Models/Соревнования.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Соревнования
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        //public Соревнования()
        //{
        //    this.Подготовка_к_соревнованиям = new HashSet<Подготовка_к_соревнованиям>();
        //}
        [Key]
        public int ID_Соревнований { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public Nullable<System.DateTime> Дата_соревнований { get; set; }
        public string Тип_соревнований { get; set; }
        public string Вид_спорта { get; set; }
        public string Спонсор_соревнований { get; set; }
        public string Город { get; set; }
        public string Адрес { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Спортсмен> Спортсменs { get; set; }
        public virtual ICollection<Сотрудники> Сотрудникиs  { get; set; }
        //        public virtual ICollection<Подготовка_к_соревнованиям> Подготовка_к_соревнованиям { get; set; }
        //      public virtual Результат Результат { get; set; }
    }
}

WebApplication1/Controllers/СоревнованияController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class СоревнованияController : Controller
    {
        private DBConnection db = new DBConnection();

        public ActionResult Index(string filter)
        {
            if (!String.IsNullOrWhiteSpace(filter))
            {
                var text = db.Соревнования.AsEnumerable();
                text = text.Where(x => x.Город == filter);
                return View(text.ToList());

            }
            return View(db.Соревнования.ToList());
        }


        // GET: Соревнования
        //public ActionResult Index()
        //{
        //    return View(db.Соревнования.ToList());
        //}

        // GET: Соревнования/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Соревнования соревнования = db.Соревнования.Find(id);
            if (соревнования == null)
            {
                return HttpNotFound();
            }
            return View(соревнования);
        }

        // GET: Соревнования/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Соревнования/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_Соревнований,Дата_соревнований,Тип_соревнований,Вид_спорта,Спонсор_соревнований,Город,Адрес")] Соревнования соревнования)
        {
            if (ModelState.IsValid)
            {
                db.Соревнования.Add(соревнования);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(соревнования);
        }

        // GET: Соревнования/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Соревнования соревнования = db.Соревнования.Find(id);
            if (соревнования == null)
            {
                return HttpNotFound();
            }
            return View(соревнования);
        }

        // POST: Соревнования/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_Соревнований,Дата_соревнований,Тип_соревнований,Вид_спорта,Спонсор_соревнований,Город,Адрес")] Соревнования соревнования)
        {
            if (ModelState.IsValid)
            {
                db.Entry(соревнования).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(соревнования);
        }

        // GET: Соревнования/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Соревнования соревнования = db.Соревнования.Find(id);
            if (соревнования == null)
            {
                return HttpNotFound();
            }
            return View(соревнования);
        }

        // POST: Соревнования/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Соревнования соревнования = db.Соревнования.Find(id);
            db.Соревнования.Remove(соревнования);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Соревнования/Create.cshtml
@model WebApplication1.Models.Соревнования

@{
    ViewBag.Title = "Create";
}

<h2>Создание</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Соревнования</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Дата_соревнований, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Дата_соревнований, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Дата_соревнований, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Тип_соревнований, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Тип_соревнований, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Тип_соревнований, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Вид_спорта, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Вид_спорта, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Вид_спорта, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Спонсор_соревнований, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Спонсор_соревнований, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Спонсор_соревнований, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Город, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Город, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Город, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Адрес, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Адрес, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Адрес, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к таблице", "Index")
</div>

WebApplication1/Views/Соревнования/Delete.cshtml
@model WebApplication1.Models.Соревнования

@{
    ViewBag.Title = "Delete";
}

<h2>Удаление</h2>

<h3>Вы уверены, что хотите удалить?</h3>
<div>
    <h4>Соревнования</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Дата_соревнований)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Дата_соревнований)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Тип_соревнований)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Тип_соревнований)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Вид_спорта)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Вид_спорта)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Спонсор_соревнований)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Спонсор_соревнований)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Город)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Город)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Адрес)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Адрес)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Вернуться к таблице", "Index")
        </div>
    }
</div>

WebApplication1/Views/Соревнования/Details.cshtml
@model WebApplication1.Models.Соревнования

@{
    ViewBag.Title = "Details";
}

<h2>Подробно</h2>

<div>
    <h4>Соревнования</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Дата_соревнований)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Дата_соревнований)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Тип_соревнований)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Тип_соревнований)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Вид_спорта)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Вид_спорта)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Спонсор_соревнований)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Спонсор_соревнований)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Город)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Город)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Адрес)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Адрес)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Редактировать", "Edit", new { id = Model.ID_Соревнований }) |
    @Html.ActionLink("Вернуться к таблице", "Index")
</p>

WebApplication1/Views/Соревнования/Edit.cshtml
@model WebApplication1.Models.Соревнования

@{
    ViewBag.Title = "Edit";
}

<h2>Редактирование</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Соревнования</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_Соревнований)

        <div class="form-group">
            @Html.LabelFor(model => model.Дата_соревнований, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Дата_соревнований, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Дата_соревнований, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Тип_соревнований, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Тип_соревнований, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Тип_соревнований, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Вид_спорта, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Вид_спорта, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Вид_спорта, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Спонсор_соревнований, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Спонсор_соревнований, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Спонсор_соревнований, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Город, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Город, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Город, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Адрес, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Адрес, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Адрес, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Вернуться к таблице", "Index")
</div>

WebApplication1/Views/Соревнования/Index.cshtml
@model IEnumerable<WebApplication1.Models.Соревнования>

@{
    ViewBag.Title = "Index";
}

<h2>Соревнования</h2>

<p>
    @Html.ActionLink("Создать", "Create")

    @using (@Html.BeginForm("Index", "Соревнования"))
    {
        @Html.TextBox("filter", "", new { style = "width:100%" })
        <br />
        <input type="submit" class="btn btn-primary" value="Отфильтровать по городу" />
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Дата_соревнований)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Тип_соревнований)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Вид_спорта)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Спонсор_соревнований)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Город)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Адрес)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Дата_соревнований)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Тип_соревнований)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Вид_спорта)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Спонсор_соревнований)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Город)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Адрес)
        </td>
        <td>
            @Html.ActionLink("Редактировать", "Edit", new { id=item.ID_Соревнований }) |
            @Html.ActionLink("Подробнее", "Details", new { id=item.ID_Соревнований }) |
            @Html.ActionLink("Удалить", "Delete", new { id=item.ID_Соревнований })
        </td>
    </tr>
}

</table>